--Magnitude Analysis
--Compare the measure values by categories
--It helps in understanding the importance of different categories

-- Find the Total nuber of customers by Country
SELECT country, COUNT(customer_key) total_customers
FROM gold.dim_customers
GROUP BY country
ORDER BY total_customers DESC;

-- Find total customers by gender
SELECT gender, COUNT(customer_key) total_customers
FROM gold.dim_customers
GROUP BY gender
ORDER BY total_customers DESC;

-- Find Total products by category
SELECT category, COUNT(product_key) total_products
FROM gold.dim_products
GROUP BY category
ORDER BY total_products DESC;

-- Find What is the average costs in each category?
SELECT category, AVG(cost) as average_cost
FROM gold.dim_products
GROUP BY category
ORDER by average_cost DESC;

-- What is the total revenue generated for each category
SELECT p.category,
	   SUM(f.sales_amount) AS total_revenue
FROM gold.fact_sales f
LEFT JOIN gold.dim_products p
ON p.product_key = f.product_key
GROUP BY p.category
ORDER BY total_revenue DESC;

--Find total revenue generated by each customer
SELECT 
	   c.customer_key,
	   c.first_name,
	   c.last_name,
	   c.customer_number,
	   SUM(f.sales_amount) AS total_revenue
FROM gold.fact_sales f
LEFT JOIN gold.dim_customers c
ON c.customer_key = f.customer_key
GROUP BY  c.customer_key,c.first_name, c.last_name, c.customer_number
ORDER BY total_revenue DESC;

-- What is the distribution of sold items across countries.
SELECT 
	   c.country,
	   SUM(f.quantity) AS total_sold_items	
FROM gold.fact_sales f
LEFT JOIN gold.dim_customers c
ON c.customer_key = f.customer_key
GROUP BY  c.country
ORDER BY total_sold_items DESC;